python _train_trans_and_query_fixed_budget.py \
    --output 'captions' \
    --adv_data_path 'images_adv_ii' \
    --clean_data_path 'clean_images' \
    --adv_text_path 'adv_coco_captions_10000.txt' \
    --tgt_text_path 'coco_captions_10000.txt' \
    --batch_size 1 \
    --num_samples 6 \
    --steps 8 \
    --epsilon 8 \
    --sigma 8 \
    --delta 'zero' \
    --num_query 10 \
    --num_sub_query 2 \
    --wandb \
    --wandb_project_name unidiff-attack \
    --wandb_run_name fixed-perturb-budget-for-query \